services:
  api_local:
    build: .
    command: ./node_modules/.bin/nodemon -L server.js
    env_file:
      - .env.local
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ./:/app # for nodemon
      - /app/node_modules # ignore local node_modules: https://stackoverflow.com/a/62799209
  mongodb:
    image: "mongo:7"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
  mongo-init:
    build:
      context: .
      dockerfile: Dockerfile.init-mongo
    depends_on:
      - mongodb
    links:
      - mongodb
  # mongo-express: # Attach GUI to database
  #   image: "mongo-express:latest"
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - mongodb
  #   environment: 
  #     ENV: local
  #     BASE_URL: http://localhost:3000
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/creditpulse?authSource=admin
  #     ME_CONFIG_MONGODB_AUTH_DATABASE: admin
